### ISSUE TITLE
APK not available

### ISSUE THREAD

**Issue by Liverhool** [pyload/pyload-android#17]
APK is not available anymore in F-Droid. Where to download?

**Comment by BKPepe** [comment]
It's back on F-droid
https://f-droid.org/packages/org.pyload.android.client/

**Comment by Eun** [comment]
DL on fdroid is broken

**Comment by GammaC0de** [comment]
Available here: https://web.archive.org/web/20141008114041/https://f-droid.org/repo/org.pyload.android.client_18.apk

And Here:
[org.pyload.android.client_18.zip](https://github.com/pyload/android-app/files/1195457/org.pyload.android.client_18.zip)

**Comment by floviolleau** [comment]
Hi,

Can someone rebuild the application on F-Droid with the new changes?

**Comment by GammaC0de** [comment]
[org.pyload.android.client_19.zip](https://github.com/pyload/pyload-android/files/2130548/org.pyload.android.client_19.zip)
