### ISSUE TITLE
Sorting Settings

### ISSUE THREAD

**Issue by UserX404** [pyload/pyload-android#25]
Hello.

Due to the count of plugins and its settings is quite high now, a functionality to search or/and list them in alphabetical order would be nice.

**Comment by GammaC0de** [comment]
Actually https://github.com/pyload/pyload-android/commit/cfde27fd707417cfb048c2e19b0794e3391c2333 list the plugins settings in alphabetical order.
It is just not included in a release :disappointed:

**Comment by UserX404** [comment]
wow
that was quiet fast. :-)
Any idea when it gets published?

**Comment by GammaC0de** [comment]
Well, I was hoping also to add a search feature before release but free spare time is hard to buy..

If you have the skills,
You can probably grab Android studio and fetch and build the master branch.

**Comment by UserX404** [comment]
No sorry, i'm not used in android coding.

**Comment by UserX404** [comment]
Issue closed due too new release
