### ISSUE TITLE
Stops connecting after pyload update to 0.4.20

### ISSUE THREAD

**Issue by efelon** [pyload/pyload-android#26]
After the update of the pyload installation to 0.4.20, when starting the (correctly configured) pyload android apk an error message pops up (translated from german):

> Server version does not match, please use pyLoad 0.4.9

No connection is possible and no data of the server is shown.

**Comment by QBANIN** [comment]
In the meantime you can grab APK with bumped version to 0.4.20 here https://dom.sobczyk.in/index.php/s/6BbPJxSysWAXdie

Uninstall old version and install this one.

**Comment by GammaC0de** [comment]
Here is a local mirror.

Just a warning:
This is not official build, use at your own risk.
[pyLoad_apk.zip](https://github.com/pyload/pyload-android/files/4304193/pyLoad_apk.zip)

**Comment by GammaC0de** [comment]
Here is official build: https://github.com/pyload/pyload-android/releases/tag/v0.3.7

**Comment by floviolleau** [comment]
Hello,

Thanks for the good job you made.

I have a question. Why dropping old Android versions just for a version check change? I have a kitkat and I cannot install it anymore.

Kind regards

**Comment by GammaC0de** [comment]
@floviolleau Because of with the current version of android studio I could not compile the app (I am not an android expert)

**Comment by QBANIN** [comment]
> Hello,
> 
> Thanks for the good job you made.
> 
> I have a question. Why dropping old Android versions just for a version check change? I have a kitkat and I cannot install it anymore.
> 
> Kind regards

Try this one https://dom.sobczyk.in/index.php/s/ps8Fnn5AEZCfrjS

**Comment by GammaC0de** [comment]
@floviolleau He is a working version: 
[org.pyload.android.client_21.zip](https://github.com/pyload/pyload-android/files/4533111/org.pyload.android.client_21.zip)
