### ISSUE TITLE
Update apk to support latest!!

### ISSUE THREAD

**Issue by oakes8585** [pyload/pyload-android#27]
Last build only supports android 0.4.9 myself and others im sure would love to see a new working version to support the latest build!!!!! Please consider this as i love pyload and im mobile 98% of the time and it would be so much more efficient than a web ui.

Thank you

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload-android/releases/tag/v0.3.7

**Comment by oakes8585** [comment]
Link not working to download apk???

**Comment by GammaC0de** [comment]
https://github.com/pyload/pyload-android/releases/download/v0.3.7/org.pyload.android.client_20.apk

**Comment by oakes8585** [comment]
Never mind working in browser not in fasthub.... thank you so much

**Comment by oakes8585** [comment]
Keeps loosing connection to server and i have no idea as to why all the settings are correct......ip,port etc im at a loss now
