### ISSUE TITLE
statusbar spacing

### ISSUE THREAD

**Issue by UserX404** [pyload/pyload-android#29]
Items in statusbar (speed, actice count,...) got sqeezed. 
![_20200404_213316](https://user-images.githubusercontent.com/14954521/78459899-bcb30700-76bc-11ea-9ea5-569986f38df9.JPG)

**Comment by GammaC0de** [comment]
Now we need a new version :(

**Comment by GammaC0de** [comment]
OK, I have update the APK in the releases section to include this fix.
