### ISSUE TITLE
Can't connect to my seedbox's Pyload

### ISSUE THREAD

**Issue by gekioo** [pyload/pyload-android#30]
I have a dedi with quickbox installed. Ubuntu 16.04 with the latest version of Pyload and Pyload apk
In APK settings:
Under Username: I have my Pyload's username which is the same as my server's login username
Under Password: I have my Pyload's password which is the same as my server's login password
Under Address: I have my server's IP address
Under Port: it's 7227
SSl connection and validate SSL certificate are disabled.

I'm getting "Lost connection. Please try to refresh"
Any help?
Edit: I'm sorry at first I've created the issue without any details by mistake

**Comment by GammaC0de** [comment]
Please explain,

You provide no information, no logs and cryptic subject,
how am I supposed to understand what and where is the problem!?

**Comment by gekioo** [comment]
> Please explain,
> 
> You provide no information, no logs and cryptic subject,
> how am I supposed to understand what and where is the problem!?

I'm sorry for this mistake. I've updated the post.

**Comment by GammaC0de** [comment]
Have you enabled port forwarding for port 7227?

**Comment by gekioo** [comment]
> Have you enabled port forwarding for port 7227?

I don't have root access and the server is managed. I've contacted my provider now and asked them to enable port forwarding for port 7227.
I'll update the post after I receive a response from them. Thank you.

**Comment by GammaC0de** [comment]
> I don't have root access and the server is managed. I've contacted my provider now and asked them to enable port forwarding for port 7227.
I'll update the post after I receive a response from them. Thank you.

Well, port forwarding is very important, without is the app cannot work..

**Comment by gekioo** [comment]
> > I don't have root access and the server is managed. I've contacted my provider now and asked them to enable port forwarding for port 7227.
> > I'll update the post after I receive a response from them. Thank you.
> 
> Well, port forwarding is very important, without is the app cannot work..

I've contacted my provider and they said that port 7227 is open and doesn't need forwarding and I've checked that it's open with a port checker. but I still can't connect to my Pyload using the Pyload apk. What should I do next?

**Comment by GammaC0de** [comment]
Hi,
These days are busy days,
If you still want me to investigate this issue, I would need access to the pyload.

If that is fine for you please say.

**Comment by GammaC0de** [comment]
No response, closing.
