### ISSUE TITLE
PyLoad connection: wrong username/password

### ISSUE THREAD

**Issue by Fomys** [pyload/pyload-android#31]
I have installed pyload on my raspberry, everything is fine, but android app not work.

I install pyload-android from github apk, version 0.3.7, pyload from github deb version 0.4.20.

In pyload-android settings I set my username/password (I check 3 times), I have tried with all configuration of ssl (I don't have ssl on pyload, I have check in config file), but I still get an error `wrong username or password` (my phone is in french so I have the message `Erreur dans l'identifiant ou le mot de passe`).

I check on pyload-web (from my android device, so I am sure that I can connect to pyload from it), api port is 7227, as in pyload-android options, and my username/password works.

I don't found any option to see log in pyload-android and I don't see any errors in pyload logs, except `ADDON ClickNLoad: [Errno 98] Address already in use` every 4 minutes, but I think it is not related to pyload-android connection).

My pyload config file says that remote connection is enabled and on port 7227:
```
remote - "Remote":                                                                                 
        bool activated : "Activated" = True                                                        
        ip listenaddr : "Adress" = 0.0.0.0                                                         
        bool nolocalauth : "No authentication on local connections" = True                         
        int port : "Port" = 7227
```

I can give you more informations if you want.

Can you help me or solve this problem? (On the python part I can help a bit, but I don't know anything about java)

I have check issue #30 but I think it is not the same error.

PS: Sorry for my english, I'm french 😓 
EDIT: Add issue number

**Comment by GammaC0de** [comment]
You have some other process already using pop 7227, 
You have to set another port.

**Comment by Fomys** [comment]
Ho yes 😓
I had an other pyload instance running (I tried to run it from sources).
Thank you very much!
