### ISSUE TITLE
color/theme

### ISSUE THREAD

**Issue by UserX404** [pyload/pyload-android#34]
After update to 0.3.7 the dark theme is gone.
I'm using Android 10 with dark theme but in the past the app always was dark.
There also is no switch to change the theme.
What has been changed and how am I able to get back the dark theme?

Edit: I'm also not able to see the file names. White fonts on white background.

![Screenshot_20200902-215817](https://user-images.githubusercontent.com/14954521/92031176-78f62380-ed68-11ea-9f69-c6c9724db07d.png)

**Comment by docgalaxyblock** [comment]
I'm having the same problem (LineageOS 16)

**Comment by UserX404** [comment]
Note: This bug not exists in 0.3.6. Runs without problems.

**Comment by GammaC0de** [comment]
Sorry guys, currently I am busy getting  pyload v0.5 stable, I have no time for this issue.

If you find a solution, you can issue a PR.
