### ISSUE TITLE
Check & request operation missing before choosing container file

### ISSUE THREAD

**Issue by aper-project** [pyload/pyload-android#39]
Hi, there, I've found a issue in version 0.3.7, which is downloaded from [F-Droid](https://f-droid.org/packages/org.pyload.android.client/).
## Description
This app does not check nd request the WRITE_EXTERNAL_STORAGE permission when I want choose a container file form storage.
There are two unexpected behaviors: 
1. choose file page is empty until I grant this permission in the system setting
2. it will crash if I continue chose Parent Directory
## Reproduce
- Step 1 : Open pyLoad and select Add Links button.
![image](https://user-images.githubusercontent.com/68948244/123601467-4bfc8b00-d82a-11eb-9db3-5ab4a7d82311.png)
- Step 2 : Click "CHOOSE" for choose container file 
Because this version does not check and request permission when I click "CHOOSE" button , no folders and files are read out on this page.
 ![image](https://user-images.githubusercontent.com/68948244/123601518-5ae33d80-d82a-11eb-9868-d718fbdce73d.png)

- Step 3 : go to system setting ,  grant the storage permission 
- Step 4 : repeat step 1 and step 2
![image](https://user-images.githubusercontent.com/68948244/123601563-66ceff80-d82a-11eb-97e8-cee2f42f2129.png)

The call chain related to this bug :
```
	org.pyload.android.client.module.FileChooser.onCreate(android.os.Bundle)void
	 org.pyload.android.client.module.FileChooser.<clinit>()void
	  android.os.Environment.getExternalStorageDirectory()java.io.File
```
@GammaC0de  
Could you help me review this issue? Very thanks!

**Comment by GammaC0de** [comment]
Android support for checking for this setting starts from android 11.

**Comment by aper-project** [comment]
> Android support for checking for this setting starts from android 11.

Which update do you refer to? It seems that Android cannot automatically check and request a certain permission. If that permission is missing and you call an API that requires the permission, it simply crashes.

Android 11's updates to the permission system: https://developer.android.com/about/versions/11/privacy/permissions

**Comment by GammaC0de** [comment]
I mean that there can be a fix for that but just for Android 11 and up, older versions (this app runs on 4.2 and up) cannot be dealt because of lack of support in the Android OS, they must set this settings manually

**Comment by aper-project** [comment]
> I mean that there can be a fix for that but just for Android 11 and up, older versions (this app runs on 4.2 and up) cannot be dealt because of lack of support in the Android OS, they must set this settings manually


https://user-images.githubusercontent.com/68948244/124410667-85c71780-dd7d-11eb-98d1-700ab618d79c.mp4

I tested it on an 11 device, and it seems that Android 11 also cannot grant that permission.

In fact, it can request for the permission programmatically, and it only requires Android 6 and above.

This is documented in Android's official [tutorial](https://developer.android.com/training/permissions/requesting#request-permission).
