### ISSUE TITLE
Play store update

### ISSUE THREAD

**Issue by chrstnwhlrt** [pyload/pyload-android#5]
Hi,
it would be great if you could just pack the current version and push it to the play store. The multiple link receiving feature (last pull request) should be reason enough ;-)
Regards

**Comment by BKPepe** [comment]
@vuolter  would it be possible or you will wait until 1.0.0? )

**Comment by vuolter** [comment]
@BKPepe I'm not registered to the play store, so I can not push there anything. :s
Rather, pyLoad 1.0 will not be compatible with the current android-app. :(

**Comment by BKPepe** [comment]
Yeah, but atleast something right now. There's not current ETA for 1.0 and maybe community will update app.
